### ISSUE TITLE
virtualspace fails to work after an update to win11 22631.3085

### ISSUE THREAD

**Issue by Zplusless** [newlooper/VirtualSpace#111]
![image](https://github.com/newlooper/VirtualSpace/assets/10062702/b557d8a7-47ab-4399-bbae-a4a603f500e6)

## info.txt:
![image](https://github.com/newlooper/VirtualSpace/assets/10062702/80cb9835-519b-4f5a-a9e6-7fa96bf080e5)

**Comment by Zplusless** [comment]
https://github.com/newlooper/VirtualSpace/issues/54#issuecomment-1477400559 this doesn't fix the problem

**Comment by Zplusless** [comment]
the win11 update is [KB5034204](https://support.microsoft.com/en-us/topic/january-23-2024-kb5034204-os-builds-22621-3085-and-22631-3085-preview-7652acf2-56dc-430e-b8ef-ec8f56ec1028)

**Comment by sytone** [comment]
Looks like multiple apps are hit by it. here is the updated guids and interfaces.

https://github.com/slnz00/VirtualDesktopDumper/blob/master/dumps/Win11-23H2-22631.3085.txt

Issues from other VD solutions.

https://github.com/Ciantic/VirtualDesktopAccessor/pull/87

https://github.com/MScholtes/VirtualDesktop/issues/78

**Comment by newlooper** [comment]
thanks for report.

i will test a new build on a VM which the update installed.

after M$ force user install the update, a new version of VS will be released.

**Comment by domanz222** [comment]
> Looks like multiple apps are hit by it. here is the updated guids and interfaces.
> 
> https://github.com/slnz00/VirtualDesktopDumper/blob/master/dumps/Win11-23H2-22631.3085.txt
> 
> Issues from other VD solutions.
> 
> [Ciantic/VirtualDesktopAccessor#87](https://github.com/Ciantic/VirtualDesktopAccessor/pull/87)
> 
> [MScholtes/VirtualDesktop#78](https://github.com/MScholtes/VirtualDesktop/issues/78)

Thanks. Looks to be a solution!

**Comment by sytone** [comment]
> thanks for report.
> 
> i will test a new build on a VM which the update installed.
> 
> after M$ force user install the update, a new version of VS will be released.

For reference this is the KB: https://support.microsoft.com/en-au/topic/january-23-2024-kb5034204-os-builds-22621-3085-and-22631-3085-preview-7652acf2-56dc-430e-b8ef-ec8f56ec1028

I was speaking with some people from the UI team so will see if we can get a better external API for the VD capabilities vs using internal. No promises.

**Comment by Zplusless** [comment]
> thanks for report.
> 
> i will test a new build on a VM which the update installed.
> 
> after M$ force user install the update, a new version of VS will be released.

It's not an insider update. All my win11 PC and laptop are forced to update.

**Comment by newlooper** [comment]
try this:

[VirtualSpace_0.2.786.355_net6.0_win-x64_noplugin.zip](https://github.com/newlooper/VirtualSpace/files/14093436/VirtualSpace_0.2.786.355_net6.0_win-x64_noplugin.zip)

not fully tested, any issues let me know.

**Comment by newlooper** [comment]
> > thanks for report.
> > i will test a new build on a VM which the update installed.
> > after M$ force user install the update, a new version of VS will be released.
> 
> It's not an insider update. All my win11 PC and laptop are forced to update.

[KB5034204](https://support.microsoft.com/en-us/topic/january-23-2024-kb5034204-os-builds-22621-3085-and-22631-3085-preview-7652acf2-56dc-430e-b8ef-ec8f56ec1028) is a preview update, i can see the update, but M$ didn't force me install it.

**Comment by sytone** [comment]
The change in GUIDs looks like it happened a while back so other patches or security releases may have had this as well.

**Comment by sytone** [comment]
The change in GUIDs looks like it happened a while back so other patches or security releases may have had this as well.

I have tried the drop you have created, and it is working, looking at the logs I am not seeing any entries indicating a problem. Let me know if you want me to look at a PR.

**Comment by mdear** [comment]
I tried 0.2.786.355 and got the following crash dump:

https://www.dropbox.com/scl/fi/ocaoyv065hhb4puqjlsao/VirtualSpace.exe_240131_141635.dmp?rlkey=lq5z55f84ziujppjblvpavy1g&dl=0

I previously had tried 0.2.698.984 and 0.2.634.669 and both crashed with latest Windows 

Edition	Windows 11 Home
Version	23H2
Installed on	‎2023-‎05-‎25
OS build	22631.3085
Experience	Windows Feature Experience Pack 1000.22684.1000.0

**Comment by sytone** [comment]
I ran that drop on another machine and it failed. Here is the stack trace, looks like an issue with the guid referencing the COM interface.

```
Application: VirtualSpace.exe
CoreCLR Version: 6.0.2623.60508
.NET Version: 6.0.26
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'VirtualDesktop.DesktopManager' threw an exception.
 ---> System.InvalidCastException: Specified cast is not valid.
   at VirtualDesktop.IServiceProvider10.QueryService(Guid& service, Guid& riid)
   at VirtualDesktop.DesktopManager.Init()
   at VirtualDesktop.DesktopManager..cctor()
   --- End of inner exception stack trace ---
   at VirtualDesktop.DesktopManager.GetDesktopCount()
   at VirtualDesktop.Desktop.get_Count()
   at VirtualSpace.VirtualDesktop.Api.DesktopWrapper.get_Count()
   at VirtualSpace.App.BootInfo()
   at VirtualSpace.App.Bootstrap()
   at VirtualSpace.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at VirtualSpace.Program.Main()
```

**Comment by Zplusless** [comment]
> try this:
> 
> [VirtualSpace_0.2.786.355_net6.0_win-x64_noplugin.zip](https://github.com/newlooper/VirtualSpace/files/14093436/VirtualSpace_0.2.786.355_net6.0_win-x64_noplugin.zip)
> 
> not fully tested, any issues let me know.

After my PC installed KB5044204 automatically again, I tried this version, and it worked well temporarily.

**Comment by Nocxr** [comment]
> > try this:
> > [VirtualSpace_0.2.786.355_net6.0_win-x64_noplugin.zip](https://github.com/newlooper/VirtualSpace/files/14093436/VirtualSpace_0.2.786.355_net6.0_win-x64_noplugin.zip)
> > not fully tested, any issues let me know.
> 
> After my PC installed KB5044204 automatically again, I tried this version, and it worked well temporarily.

Can also confirm this is working after my system rebooted and installed said updates last night

**Comment by kranix0** [comment]
> try this:
> 
> [VirtualSpace_0.2.786.355_net6.0_win-x64_noplugin.zip](https://github.com/newlooper/VirtualSpace/files/14093436/VirtualSpace_0.2.786.355_net6.0_win-x64_noplugin.zip)
> 
> not fully tested, any issues let me know.

Doesn't work for me 😔

Edition	Windows 11 Pro
Version	22H2
Installed on	‎Tue ‎14/‎02/‎2023
OS build	22621.3155
Experience	Windows Feature Experience Pack 1000.22684.1000.0

**Comment by mdear** [comment]
I'm still dead in the water, I miss VirtualSpace

Edition	Windows 11 Home
Version	23H2
Installed on	‎2023-‎05-‎25
OS build	22631.3155
Experience	Windows Feature Experience Pack 1000.22684.1000.0

**Comment by kranix0** [comment]
> Edition Windows 11 Pro Version 22H2 Installed on ‎Tue ‎14/‎02/‎2023 OS build 22621.3155 Experience Windows Feature Experience Pack 1000.22684.1000.0

It seems OK now. I don't know what's changed. I even upgraded Windows to 22631.3155 and it kept working.
