### ISSUE TITLE
There is a bug when you right-click on the blank space, and you must restart the app to recover

### ISSUE THREAD

**Issue by dsfa4adswf48** [newlooper/VirtualSpace#114]
There is a bug when you right-click on the blank space, and you must restart the app to recover
![image](https://github.com/newlooper/VirtualSpace/assets/55836815/19550a2f-65c4-4b8c-88d3-96ad22a6e810)

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.Runtime.InteropServices.COMException (0x8002802B): 找不到元素。 (0x8002802B (TYPE_E_ELEMENTNOTFOUND))
   at VirtualDesktop.IApplicationViewCollection.GetViewForHWnd(IntPtr hWnd, IApplicationView& view)
   at VirtualDesktop.Desktop.IsWindowPinned(IntPtr hWnd)
   at VirtualSpace.VirtualDesktop.Menus.VdCtm(MenuInfo mi)
   at VirtualSpace.VirtualDesktop.VirtualDesktopWindow.VirtualDesktopWindow_MouseUp(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at VirtualSpace.VirtualDesktop.VirtualDesktopWindow.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
System.Private.CoreLib
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Private.CoreLib.dll
----------------------------------------
VirtualSpace
    程序集版本:0.2.786.355
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Runtime.dll
----------------------------------------
Logger
    程序集版本:1.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
PresentationFramework
    程序集版本:6.0.2.0
    Win32 版本:6.0.1022.47604
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.10/PresentationFramework.dll
----------------------------------------
WindowsBase
    程序集版本:6.0.2.0
    Win32 版本:6.0.1022.47604
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.10/WindowsBase.dll
----------------------------------------
System.Xaml
    程序集版本:6.0.2.0
    Win32 版本:6.0.1022.47604
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.10/System.Xaml.dll
----------------------------------------
Serilog
    程序集版本:2.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
netstandard
    程序集版本:2.1.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/netstandard.dll
----------------------------------------
System.Collections
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Collections.dll
----------------------------------------
Serilog.Sinks.File
    程序集版本:5.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Linq
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Linq.dll
----------------------------------------
System.IO.FileSystem
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.IO.FileSystem.dll
----------------------------------------
System.Text.Encoding.Extensions
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Private.Uri
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Private.Uri.dll
----------------------------------------
System.IO.Packaging
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.10/System.IO.Packaging.dll
----------------------------------------
PresentationCore
    程序集版本:6.0.2.0
    Win32 版本:6.0.1022.47604
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.10/PresentationCore.dll
----------------------------------------
DirectWriteForwarder
    程序集版本:6.0.2.0
    Win32 版本:6,0,1022,47604 @Commit: 3bbc77257e3d51a2e19195523eafd262da1f5459
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.10/DirectWriteForwarder.dll
----------------------------------------
System.Runtime.Extensions
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Runtime.Extensions.dll
----------------------------------------
System.Runtime.InteropServices
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Runtime.InteropServices.dll
----------------------------------------
System.Runtime.CompilerServices.VisualC
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Runtime.CompilerServices.VisualC.dll
----------------------------------------
System.Diagnostics.Debug
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Diagnostics.Debug.dll
----------------------------------------
System.Threading
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Threading.dll
----------------------------------------
Microsoft.Win32.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/Microsoft.Win32.Primitives.dll
----------------------------------------
System.Collections.NonGeneric
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Collections.NonGeneric.dll
----------------------------------------
Microsoft.Win32.Registry
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/Microsoft.Win32.Registry.dll
----------------------------------------
System.Collections.Specialized
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Collections.Specialized.dll
----------------------------------------
System.ComponentModel.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.ComponentModel.Primitives.dll
----------------------------------------
System.Threading.Thread
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Threading.Thread.dll
----------------------------------------
System.Configuration.ConfigurationManager
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.10/System.Configuration.ConfigurationManager.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Diagnostics.Process
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Diagnostics.Process.dll
----------------------------------------
System.Memory
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Memory.dll
----------------------------------------
System.Xml.ReaderWriter
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Private.Xml.dll
----------------------------------------
System.Net.WebClient
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Net.WebClient.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
Configuration
    程序集版本:1.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
IpcServer
    程序集版本:1.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
PluginHost
    程序集版本:1.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Bridge
    程序集版本:1.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.IO.Pipes
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.IO.Pipes.dll
----------------------------------------
System.Text.Json
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Text.Json.dll
----------------------------------------
Ipc
    程序集版本:1.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Plugin
    程序集版本:1.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Collections.Concurrent
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Collections.Concurrent.dll
----------------------------------------
Helpers
    程序集版本:1.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Threading.Channels
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Threading.Channels.dll
----------------------------------------
System.Threading.ThreadPool
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Threading.ThreadPool.dll
----------------------------------------
System.Security.AccessControl
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Security.AccessControl.dll
----------------------------------------
System.Security.Principal.Windows
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Security.Principal.Windows.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Reflection.Primitives.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Text.Encodings.Web
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Text.Encodings.Web.dll
----------------------------------------
System.Runtime.Intrinsics
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Runtime.Intrinsics.dll
----------------------------------------
System.Numerics.Vectors
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Numerics.Vectors.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Linq.Expressions
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Linq.Expressions.dll
----------------------------------------
Microsoft.CSharp
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/Microsoft.CSharp.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    程序集版本:0.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Private.CoreLib.dll
----------------------------------------
System.Windows.Forms
    程序集版本:6.0.2.0
    Win32 版本:6.0.1022.47606
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.10/System.Windows.Forms.dll
----------------------------------------
System.Drawing.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Drawing.Primitives.dll
----------------------------------------
VirtualDesktopWrapper
    程序集版本:1.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Windows.Forms.Primitives
    程序集版本:6.0.2.0
    Win32 版本:6.0.1022.47606
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.10/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Security.Claims
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Security.Claims.dll
----------------------------------------
System.Management
    程序集版本:4.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.Win32.SystemEvents
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
VirtualDesktop10
    程序集版本:1.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Private.CoreLib.dll
----------------------------------------
VirtualDesktop11_21H2
    程序集版本:1.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Private.CoreLib.dll
----------------------------------------
System.Drawing.Common
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Diagnostics.TraceSource
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Diagnostics.TraceSource.dll
----------------------------------------
System.ComponentModel.TypeConverter
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.ComponentModel.TypeConverter.dll
----------------------------------------
Bridge.resources
    程序集版本:1.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.ComponentModel
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.ComponentModel.dll
----------------------------------------
Notification.Wpf
    程序集版本:6.1.0.1
    Win32 版本:不可用
    代码库:
----------------------------------------
LinqExpressionBuilder
    程序集版本:1.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.ObjectModel
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.ObjectModel.dll
----------------------------------------
System.Text.RegularExpressions
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Text.RegularExpressions.dll
----------------------------------------
ControlPanel
    程序集版本:1.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
ControlPanel.resources
    程序集版本:1.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Windows.Extensions
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.10/System.Windows.Extensions.dll
----------------------------------------
System.Net.Requests
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Net.Requests.dll
----------------------------------------
System.Net.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Net.Primitives.dll
----------------------------------------
System.Net.WebHeaderCollection
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Net.WebHeaderCollection.dll
----------------------------------------
MaterialDesignThemes.Wpf
    程序集版本:4.8.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
UIAutomationTypes
    程序集版本:6.0.2.0
    Win32 版本:6.0.1022.47604
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.10/UIAutomationTypes.dll
----------------------------------------
PresentationFramework.Aero2
    程序集版本:6.0.2.0
    Win32 版本:6.0.1022.47604
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.10/PresentationFramework.Aero2.dll
----------------------------------------
WPFLocalizeExtension
    程序集版本:3.10.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Resources.ResourceManager
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Resources.ResourceManager.dll
----------------------------------------
XAMLMarkupExtensions
    程序集版本:2.1.3.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Windows.Controls.Ribbon
    程序集版本:6.0.2.0
    Win32 版本:6.0.1022.47604
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.10/System.Windows.Controls.Ribbon.dll
----------------------------------------
System.Runtime.Loader
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Runtime.Loader.dll
----------------------------------------
PresentationFramework.resources
    程序集版本:6.0.2.0
    Win32 版本:6.0.1022.47604
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.10/zh-Hans/PresentationFramework.resources.dll
----------------------------------------
UIAutomationProvider
    程序集版本:6.0.2.0
    Win32 版本:6.0.1022.47604
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.10/UIAutomationProvider.dll
----------------------------------------
PresentationFramework-SystemXml
    程序集版本:6.0.2.0
    Win32 版本:6.0.1022.47604
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.10/PresentationFramework-SystemXml.dll
----------------------------------------
Microsoft.Win32.TaskScheduler
    程序集版本:2.10.1.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Diagnostics.FileVersionInfo
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
PresentationCore.resources
    程序集版本:6.0.2.0
    Win32 版本:6.0.1022.47604
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.10/zh-Hans/PresentationCore.resources.dll
----------------------------------------
MaterialDesignColors
    程序集版本:2.1.2.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:6.0.1022.47606
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.10/Accessibility.dll
----------------------------------------
System.Security.Cryptography.Algorithms
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Security.Cryptography.Algorithms.dll
----------------------------------------
System.Security.Cryptography.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Runtime.Serialization.Formatters.dll
----------------------------------------
WinRT.Runtime
    程序集版本:1.4.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
PresentationFramework-SystemCore
    程序集版本:6.0.2.0
    Win32 版本:6.0.1022.47604
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.10/PresentationFramework-SystemCore.dll
----------------------------------------
System.Diagnostics.StackTrace
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Threading.Overlapped
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Threading.Overlapped.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:6.0.2.0
    Win32 版本:6.0.1022.47606
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.10/zh-Hans/System.Windows.Forms.resources.dll
----------------------------------------
System.Reflection.Metadata
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    程序集版本:6.0.0.0
    Win32 版本:6.0.1022.47605
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Collections.Immutable.dll
----------------------------------------

************** JIT 调试 **************

**Comment by dsfa4adswf48** [comment]
My computer system is Windows10 version 21H1 (OS Build 19043.1165)
