### ISSUE TITLE
Cannot download latest release (Dec 2024) due to reported virus

### ISSUE THREAD

**Issue by mdear** [newlooper/VirtualSpace#133]
I'm trying to download the full VirtualSpace (with plugins) zipfile from https://github.com/newlooper/VirtualSpace/releases/tag/Build-0.2.1104

but my Brave browser refuses to download, stating it has detected a virus.

Please tell me how I can get a copy of your newest release without circumventing virus checks.

**Comment by mdear** [comment]
![image](https://github.com/user-attachments/assets/6f08de55-a709-4013-bf5d-26925178d3ca)

**Comment by newlooper** [comment]
should be a false positives.
use more antivirus app to test the zip file. see the difference.
and the McAfee told user can restore it.

**Comment by mdear** [comment]
![image](https://github.com/user-attachments/assets/1c0d7674-e89b-48ab-8112-be4a1bd6000e)

![image](https://github.com/user-attachments/assets/24eae8a9-a0f3-45f1-b1f0-a5eed902fa88)

**Comment by mdear** [comment]
Ok, 11 out of 67 online virus scanners on VirusTotal reported an issue.  I'll give it a try.  I haven't seen Norton complain, which is my main go-to, I'll keep you advised.  Norton sent the file for online analysis but its scanners didn't detect any issue.   Thanks.

**Comment by mdear** [comment]
Got the following error when trying to invoke the Main View (after assigning it to <Windows><Ctl><Tab> and saving this keybinding

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

```
************** Exception Text **************
System.ArgumentException: Parameter is not valid.
   at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
   at System.Drawing.Bitmap..ctor(String filename, Boolean useIcm)
   at System.Drawing.Bitmap..ctor(String filename)
   at VirtualSpace.Helpers.Images.GetScaledBitmap(Int32 width, Int32 height, String path, Wallpaper& wp, String cachePath, Int64 quality)
   at VirtualSpace.Helpers.WinRegistry.GetWallpaperByPath(String path, Int32 width, Int32 height, String cachePath, Int64 quality)
   at VirtualSpace.VirtualDesktop.VirtualDesktopWindow.NormalPaint(ValueTuple`3 wpInfo, PaintEventArgs e)
   at VirtualSpace.VirtualDesktop.VirtualDesktopWindow.pbWallpaper_Paint(Object sender, PaintEventArgs e)
   at System.Windows.Forms.Control.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Form.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at VirtualSpace.VirtualDesktop.VirtualDesktopWindow.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Private.CoreLib.dll
----------------------------------------
VirtualSpace
    Assembly Version: 0.2.1104.1021
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Runtime.dll
----------------------------------------
Logger
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
PresentationFramework
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.3624.51603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.36/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.3624.51603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.36/WindowsBase.dll
----------------------------------------
System.Xaml
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.3624.51603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.36/System.Xaml.dll
----------------------------------------
Serilog
    Assembly Version: 2.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/netstandard.dll
----------------------------------------
System.Collections
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Collections.dll
----------------------------------------
Serilog.Sinks.File
    Assembly Version: 5.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Linq
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Linq.dll
----------------------------------------
System.IO.FileSystem
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.IO.FileSystem.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Private.Uri.dll
----------------------------------------
System.IO.Packaging
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.36/System.IO.Packaging.dll
----------------------------------------
PresentationCore
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.3624.51603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.36/PresentationCore.dll
----------------------------------------
DirectWriteForwarder
    Assembly Version: 6.0.2.0
    Win32 Version: 6,0,3624,51603 @Commit: a7dff252f2a6b0ff48ffe946a20584f61282aa13
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.36/DirectWriteForwarder.dll
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Runtime.Extensions.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Runtime.InteropServices.dll
----------------------------------------
System.Runtime.CompilerServices.VisualC
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Runtime.CompilerServices.VisualC.dll
----------------------------------------
System.Diagnostics.Debug
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Diagnostics.Debug.dll
----------------------------------------
System.Threading
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Threading.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/Microsoft.Win32.Primitives.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Collections.NonGeneric.dll
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/Microsoft.Win32.Registry.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Collections.Specialized.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.ComponentModel.Primitives.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Threading.Thread.dll
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.36/System.Configuration.ConfigurationManager.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Diagnostics.Process.dll
----------------------------------------
System.Memory
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Memory.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Private.Xml.dll
----------------------------------------
System.Net.WebClient
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Net.WebClient.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
Configuration
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
IpcServer
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
PluginHost
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Bridge
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.IO.Pipes
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.IO.Pipes.dll
----------------------------------------
System.Text.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Text.Json.dll
----------------------------------------
Ipc
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Plugin
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Collections.Concurrent.dll
----------------------------------------
Helpers
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Threading.Channels
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Threading.Channels.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Threading.ThreadPool.dll
----------------------------------------
System.Security.AccessControl
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Security.AccessControl.dll
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Security.Principal.Windows.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Drawing.Primitives.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.3624.51513
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.36/System.Windows.Forms.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Linq.Expressions.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/Microsoft.CSharp.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Reflection.Primitives.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Private.CoreLib.dll
----------------------------------------
System.Text.Encodings.Web
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Text.Encodings.Web.dll
----------------------------------------
System.Runtime.Intrinsics
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Runtime.Intrinsics.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Numerics.Vectors.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
VirtualDesktopWrapper
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.3624.51513
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.36/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Security.Claims
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Security.Claims.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
VirtualDesktop10
    Assembly Version: 1.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Private.CoreLib.dll
----------------------------------------
VirtualDesktop11_24H2
    Assembly Version: 1.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Private.CoreLib.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 7.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Diagnostics.TraceSource.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.ComponentModel.dll
----------------------------------------
Notification.Wpf
    Assembly Version: 6.1.0.1
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
LinqExpressionBuilder
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.ObjectModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.ObjectModel.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Text.RegularExpressions.dll
----------------------------------------
ControlPanel
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Windows.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.36/System.Windows.Extensions.dll
----------------------------------------
System.Net.Requests
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Net.Requests.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Net.Primitives.dll
----------------------------------------
System.Net.WebHeaderCollection
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Net.WebHeaderCollection.dll
----------------------------------------
MaterialDesignThemes.Wpf
    Assembly Version: 4.8.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
UIAutomationTypes
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.3624.51603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.36/UIAutomationTypes.dll
----------------------------------------
PresentationFramework.Aero2
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.3624.51603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.36/PresentationFramework.Aero2.dll
----------------------------------------
WPFLocalizeExtension
    Assembly Version: 3.10.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Resources.ResourceManager
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Resources.ResourceManager.dll
----------------------------------------
XAMLMarkupExtensions
    Assembly Version: 2.1.3.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
ControlPanel.resources
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Windows.Controls.Ribbon
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.3624.51603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.36/System.Windows.Controls.Ribbon.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Runtime.Loader.dll
----------------------------------------
UIAutomationProvider
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.3624.51603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.36/UIAutomationProvider.dll
----------------------------------------
PresentationFramework-SystemXml
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.3624.51603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.36/PresentationFramework-SystemXml.dll
----------------------------------------
Microsoft.Win32.TaskScheduler
    Assembly Version: 2.10.1.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
MaterialDesignColors
    Assembly Version: 2.1.2.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.3624.51513
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.36/Accessibility.dll
----------------------------------------
WinRT.Runtime
    Assembly Version: 1.4.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Security.Cryptography.Algorithms
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Security.Cryptography.Algorithms.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Diagnostics.StackTrace.dll
----------------------------------------
PresentationFramework-SystemCore
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.3624.51603
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.36/PresentationFramework-SystemCore.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3624.51421
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Collections.Immutable.dll
----------------------------------------

************** JIT Debugging **************
```
